### ISSUE TITLE
JointHandle should be managed using DynamicJointState message

### ISSUE THREAD

**Issue by jordan-palacios** [ros-controls/ros2_control#124]
This is a follow up on #112 and involves modifying joint handles so they make use of the DynamicJointState message. `JointHandle` works the same way as `ActuatorHandle` and, in fact, makes sense for both to share a base class.

Furthermore, the goal is to remove `JointStateHandle` and `JointCommandHandle` completely. `JointStateHandle` currently has the downside of being hardcoded to the position, velocity and effort interfaces. Once done, `JointStateHandle` and `JointCommandHandle` could be managed by `JointHandle` instead.

The problem with the current joint handles is that they are being largely used across `ros2_control` and `ros2_controllers`. Instead of doing the migration in one huge PR I was thinking in splitting it in smaller ones that we can then review and approve in succession.

The current plan is to:

- [x] Add support for `JointHandle` in `RobotHardware` and `TestRobotHardware`, they will coexist with the old handles. See #125 and #136 
- [x] Implement the new `ForwardCommandController` as a prove of concept. It will use the new handles. See https://github.com/ros-controls/ros2_controllers/issues/78
- [x] Port over all remaining controllers to the new joint handles. See https://github.com/ros-controls/ros2_controllers/issues/89
- [x] Remove completely the usage of `JointStateHandle` and `JointCommandHandle` from `RobotHardware`. See #134

**Comment by jordan-palacios** [comment]
All required tasks have been completed.
