### ISSUE TITLE
Post-Foxy breaking changes (Collection Ticket)

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#314]
Let's collect the known API/ABI breaking changes we'd like to see in a release coming after Foxy.

* [x] Not an issue anymore, rclcpp deprecations took care of it. ~~Move constants out of class & refactor to avoid lengthy casting in [controller_manager constants issue](https://github.com/ros-controls/ros2_control/pull/312/files#r568395744)~~
* [x] Update actions: [ros2_controllers#111](https://github.com/ros-controls/ros2_controllers/pull/111) @tylerjw 
* [x] Remove BOOST compiler defintions from CMakeLists.txt files in rolling/galactic  https://github.com/ros-controls/ros2_control/issues/184
* [x] ~~Use LifecycleNode once transitions cannot be triggered by externals. https://github.com/ros-controls/ros2_control/issues/266~~ @vatanaksoytezer
* [x] Hardware component lifecycle https://github.com/ros-controls/ros2_control/pull/503
* [x]  Remove controller_name from init function in ControllerInterface https://github.com/ros-controls/ros2_control/issues/251
* [x] https://github.com/ros-controls/ros2_control/issues/438
* [x] https://github.com/ros-controls/ros2_control/pull/516
* [x] https://github.com/ros-controls/ros2_control/pull/511
* [x] https://github.com/ros-controls/ros2_control/pull/515
* [x] https://github.com/ros-controls/ros2_control/pull/514
* [x] Per-controller update rate v1 https://github.com/ros-controls/ros2_control/pull/513

**Comment by tylerjw** [comment]
> Move constants out of class & refactor to avoid lengthy casting in controller_manager constants issue

The lengthy cast seems to be gone: https://github.com/ros-controls/ros2_control/blob/7a0d5169c6a0f4aa8381b0e57de22ee28e6172bf/controller_manager/include/controller_manager/controller_manager.hpp#L126

**Comment by tylerjw** [comment]
I rebased 111 on ros2_controllers here: https://github.com/ros-controls/ros2_controllers/pull/237  It needs the CI job approved before it can run because this is my first time opening a PR here.

**Comment by bmagyar** [comment]
Thanks for everyone who helped out, releases are now on the way!
